services:
  db:
    build:
      context: ./db/
    ports:
      - "5432:5432"
    env_file:
      - .env
  backend:
    depends_on:
      - db
    build: ./backend/
    ports:
      - "8080:8080"
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend/
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
