#
# Copyright (c) 2025. Created by zimnyciechan
# Github: rempek99
# ???
#

spring.application.name=eventice
server.port=8080
server.servlet.context-path=/api

# Render database credentials
#spring.datasource.url=jdbc:postgresql://dpg-cvqo7sk9c44c73bimlgg-a.frankfurt-postgres.render.com/backend_database_w7j7
#spring.datasource.username=backend
#spring.datasource.password=VdjzymyUHSwBsDFAs2yel0fPsxVLWrA6

# Docker database credentials
spring.datasource.url=jdbc:postgresql://localhost:5432/backend_database
spring.datasource.username=postgres
spring.datasource.password=changeitlater

## Hibernate properties
spring.jpa.hibernate.ddl-auto=create-drop
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.open-in-view=false

# For init data.sql scripts on start
spring.sql.init.mode=ALWAYS
spring.jpa.defer-datasource-initialization=true

# JWT Security settings
security.jwt.secret-key=27f7bbc8db7a0f14e77ccde6008420aee938ad0a4a08ff5126fe3f05afae99bb
# 1h in millisecond
security.jwt.expiration-time=3600000

# Printing all added filters to the filter chain
logging.level.org.springframework.security.web.DefaultSecurityFilterChain=DEBUG
logging.level.org.springframework.security=DEBUG

# Default security credentials (DEVELOP)
spring.security.user.name=zimny
spring.security.user.password=ciechan


