#
# Copyright (c) 2025. Created by zimnyciechan
# Github: rempek99
# ???
#

spring.application.name=eventice
server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://dpg-cvqo7sk9c44c73bimlgg-a.frankfurt-postgres.render.com/backend_database_w7j7
spring.datasource.username=backend
spring.datasource.password=VdjzymyUHSwBsDFAs2yel0fPsxVLWrA6

## Hibernate properties
spring.jpa.hibernate.ddl-auto=create-drop
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.open-in-view=false

# For init data.sql scripts on start
spring.sql.init.mode=ALWAYS
spring.jpa.defer-datasource-initialization=true

# JWT Security settings
security.jwt.secret-key=27f7bbc8db7a0f14e77ccde6008420aee938ad0a4a08ff5126fe3f05afae99bb
# 1h in millisecond
security.jwt.expiration-time=3600000

