# Render database credentials
spring.datasource.url=jdbc:postgresql://localhost:5432/backend_database
spring.datasource.username=backend
spring.datasource.password=VdjzymyUHSwBsDFAs2yel0fPsxVLWrA6

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Logging
logging.level.org.hibernate.SQL=DEBUG