# Render database credentials
spring.datasource.url=jdbc:postgresql://dpg-d3jc8nq4d50c73f3glu0-a.oregon-postgres.render.com/backend_database_kpoc
spring.datasource.username=eventice_admin
spring.datasource.password=WHrEPLjd17CKv6j99oi8LxKMPP3NPOWV

# Hibernate properties
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

# Logging
logging.level.org.hibernate.SQL=DEBUG