FROM postgres:16

ENV POSTGRES_USER=zimny
ENV POSTGRES_PASSWORD=ciechan
ENV POSTGRES_DB=EVENTICE_DB

# ARG DB_USERNAME=zimny
# ARG DB_PASSWORD=ciechan
# ARG DB_NAME=eventice_db 

# # Skrypt inicjalizacyjny
# COPY init-db.sh /docker-entrypoint-initdb.d/init-db.sh
# COPY .env .env
# RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh