#
# Copyright (c) 2025. Created by zimnyciechan
# Github: rempek99
# ???
#

spring.application.name=eventice
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/backend_database
spring.datasource.username=backend
spring.datasource.password=backend-pass123

## Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# JWT Security settings
security.jwt.secret-key=27f7bbc8db7a0f14e77ccde6008420aee938ad0a4a08ff5126fe3f05afae99bb
# 1h in millisecond
security.jwt.expiration-time=3600000

