name: Code Review with AI and Lint

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
permissions: write-all
jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run AI Code Review
        uses: Codium-ai/pr-agent@main
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
  npm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24.9.0" # Specify the Node.js version

      - name: Install dependencies
        working-directory: ./eventice-frontend
        run: npm install

      - name: Run ESLint
        working-directory: ./eventice-frontend
        run: npm run lint
