name: Test

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"
          cache: maven

      # 3. Build JAR with Maven (including tests)
      - name: Build JAR with Maven
        working-directory: ./eventice-backend/
        run: mvn --batch-mode --update-snapshots verify
